management:
  security:
    enabled: false

server:
  port: 9191

spring:
  application:
    name: vkbo
  profiles:
    active: production
  jpa:
    properties:
      hibernate:
        default_schema: SCH_VKBO
  #artemis:
    #mode: native
    #host: localhost
    #port: 61616
    #user: admin
    #password: admin
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

flyway:
  enabled: false

jms:
  magdagwy2vkbo:
    queue:
      destination: HerlaadOnderneming

routes:
  vkbo:
    magdagwy2vkbo:
      jms:
        queuename: magdagwy2vkbo
        delay: 5000