spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=ORACLE;INIT=CREATE SCHEMA IF NOT EXISTS SCH_VKBO
    platform: h2
    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true

server:
  contextPath: /vkbo

flyway:
  enabled: false
  
service:
  codes:
    url: bla

routes:
  vkbo:
    magdagwy2vkbo:
      jms:
        host: tcp://localhost:61616
        username: admin
        password: admin
    magdagwy:
      hostname: localhost
      port: 9090